[package]
name = "sike"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
binrw = "0.14.1"
clap = { version = "4.5.28", features = ["derive"] }
object = { version = "0.36.7", features = ["write"] }
